# The Docker image that will be used to build your app
image: node:20.10.0

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
    - npm run dev
  artifacts:
    paths:
      - out

deploy:
  stage: deploy
  script:
    - echo "Deploy your static Next.js files here"
  only:
    - master
