image: node:20.10.0

stages:
  - build
  - deploy

before_script:
  - nvm install
  - nvm use
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - out

deploy:
  stage: deploy
  script:
    - echo "Deploy your static Next.js files here"
  only:
    - master
