import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Erth Liner Cargo Express Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const imagePath = process.env.NODE_ENV === "development" ? "" : process.env.NEXT_PUBLIC_IMAGE_PREFIX
  return (
    <html lang="en">
      <head>
         <base href={imagePath}/>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        />
        <link rel="icon" href="/assets/svg/logo.svg" type="image/x-icon" />
        <link
          rel="shortcut icon"
          href="/assets/svg/logo.svg"
          type="image/x-icon"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
