import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FacebookMsg from "@/components/FacebookMsg";
import UrlFormater from "@/lib/UrlFormater";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Erth Liner Cargo Express Co.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const imagePath = UrlFormater("/assets/svg/logo.svg");

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        />
        <link rel="icon" href={imagePath} type="image/x-icon" />
        <link rel="shortcut icon" href={imagePath} type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <main>
          {children}
          <FacebookMsg />
        </main>
      </body>
    </html>
  );
}
